default:
    trainer: ppo
    #common
    batch_size: 256 #faster (for discrete)
    buffer_size: 5120 #faster (for discrete)
    hidden_units: 128
    learning_rate: 3.0e-4
    learning_rate_schedule: linear
    max_steps: 1.0e7
    normalize: false
    num_layers: 2
    time_horizon: 1024
    summary_freq: 1000
    vis_encode_type: simple

    #memory
    memory_size: 128
    sequence_length: 12 #smaller sequence length because there usually aren't that many needed steps
    use_recurrent: true #Because there aren't a lot of immediate rewards

    #PPO
    beta: 2.0e-4 #less beta (faster)
    epsilon: 0.3 #Makes less stable but faster
    lambd: 0.9 #less lambd for more imediate rewards (faster)
    num_epoch: 6

    reward_signals:
        extrinsic:
            strength: 1.0
            gamma: 0.99

#The goal here was to create a lighter training Config to see if it learns faster and generalizes better
