default:
    trainer: ppo
    #common
    batch_size: 512
    buffer_size: 51200
    hidden_units: 128
    learning_rate: 3.0e-4
    learning_rate_schedule: linear
    max_steps: 1.0e7
    normalize: false
    num_layers: 2
    time_horizon: 1024
    summary_freq: 1000
    vis_encode_type: simple

    #memory
    memory_size: 128
    sequence_length: 12 #smaller sequence length because there usually aren't that many needed steps
    use_recurrent: true #Because there aren't a lot of immediate rewards

    #PPO
    beta: 1.0e-4 #If entropy drops too quickly, increase beta. If entropy drops too slowly, decrease 
    epsilon: 0.2
    lambd: 0.95
    num_epoch: 6

    reward_signals:
        extrinsic:
            strength: 1.0
            gamma: 0.99

