default:
    trainer: ppo
    #common
    batch_size: 512
    buffer_size: 51200
    hidden_units: 128
    learning_rate: 5.0e-4
    learning_rate_schedule: linear
    max_steps: 1.0e7 #Maximum
    normalize: false
    num_layers: 1 #For simpler problems fewer layers are expected to train faster and more efficently, 1-3
    time_horizon: 1024
    summary_freq: 1000
    vis_encode_type: simple

    #memory
    memory_size: 128
    sequence_length: 12 #smaller sequence length because there usually aren't that many needed steps
    use_recurrent: true #Because there aren't a lot of immediate rewards

    #PPO
    beta: 1.0e-3
    epsilon: 0.2
    lambd: 0.95
    num_epoch: 6

    reward_signals:
        extrinsic:
            strength: 1.0
            gamma: 0.99

#The goal here was to create a lighter training Config to see if it learns faster and generalizes better
