default:
    trainer: sac
    #common
    batch_size: 512
    buffer_size: 50000
    hidden_units: 420
    learning_rate: 3.0e-5
    learning_rate_schedule: linear
    max_steps: 5.0e5
    normalize: false
    num_layers: 2
    time_horizon: 1024
    summary_freq: 1000
    vis_encode_type: simple

    #memory
    memory_size: 128
    sequence_length: 64
    use_recurrent: true #Because there aren't a lot of immediate rewards

    #sac
    buffer_init_steps: 500
    init_entcoef: 0.30 #to have some degree of exploration in the beggining
    save_replay_buffer: false #false because unity is slow and I don't have a lot of free disk space
    tau: 0.005
    steps_per_update: 1 #Unity is taking a long time to update so this value is 1

    reward_signals:
        extrinsic:
            strength: 1.0
            gamma: 0.99

#The goal here was to see what differences existed between ppo and sac 
