default:
    trainer: ppo
    batch_size: 512
    beta: 5.0e-3
    buffer_size: 5120
    epsilon: 0.2
    hidden_units: 420
    lambd: 0.925
    learning_rate: 3.0e-5
    learning_rate_schedule: linear
    max_steps: 5.0e5
    memory_size: 128 
    normalize: false
    num_epoch: 6
    num_layers: 2
    time_horizon: 1024
    sequence_length: 64
    summary_freq: 1000
    use_recurrent: true #Because there isn't a lot of immediate reward
    vis_encode_type: simple
    reward_signals:
        extrinsic:
            strength: 1.0
            gamma: 0.99

#The goal here was to create a balanced training Config
#Some values were scaled down from the first attempt to make for faster training and less Unity Crashes
